version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/db_buku
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=215410049
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/db_buku
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=215410049
      - POSTGRES_DB=215410049
    ports:
      - "5432:5432"
