services:
  - type: web
    name: quarkus-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/quarkus-app/quarkus-run.jar
